version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
    - 14.14.30
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: next
    versions:
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
